{{- range .Values.services }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .name }}-default-deny
  namespace: {{ $.Release.Namespace }}
spec:
  podSelector: {matchLabels: {app.kubernetes.io/name: {{ .name }}}}
  policyTypes: [Ingress, Egress]
{{- end }}
