{{- range .Values.services }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    noosfera.io/family: {{ .family }}
automountServiceAccountToken: false
{{- end }}
